apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  params:
    - default: /workspace/docker-source/Dockerfile
      description: The path to the dockerfile to build
      name: pathToDockerFile
      type: string
    - default: /workspace/docker-source
      description: The build context used by Kaniko (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      name: pathToContext
      type: string
  resources:
    inputs:
      - name: docker-source
        type: git
    outputs:
      - name: builtImage
        type: image
  steps:
    - args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(outputs.resources.builtImage.url)
        - --context=$(inputs.params.pathToContext)
      command:
        - /kaniko/executor
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker/
      image: gcr.io/kaniko-project/executor:v1.6.0
      name: build-and-push
      resources: {}